### ISSUE TITLE
Session deadlock between "in-progress" data queries and prepareDataQuery

### ISSUE THREAD

**Issue by eivanov89** [ydb-platform/ydb-jdbc-driver#32]
Hi,

I found a deadlock. Consider a multi step transaction, which does the following:
1. Prepares query, executes data query (after this step connection state holds Session object).
2. Prepares one more query. [Here](https://github.com/ydb-platform/ydb-jdbc-driver/blob/e3b19735b095a932c09722305c6af2787ee1c59e/jdbc/src/main/java/tech/ydb/jdbc/impl/YdbConnectionImpl.java#L354) it tries to obtain one more Session, while having one inside its state.

If there is enough parallel transactions to exhaust session pool on step 1, they will deadlock on step 2. Besides possible deadlock there is performance issue: we establish extra session for each Prepare, other transactions wait more time to get Session.

The possible fix might be similar to this:
```diff
diff --git a/jdbc/src/main/java/tech/ydb/jdbc/connection/YdbConnectionImpl.java b/jdbc/src/main/java/tech/ydb/jdbc/connection/YdbConnectionImpl.java
index 112d64d..37eebef 100644
--- a/jdbc/src/main/java/tech/ydb/jdbc/connection/YdbConnectionImpl.java
+++ b/jdbc/src/main/java/tech/ydb/jdbc/connection/YdbConnectionImpl.java
@@ -310,14 +310,24 @@ public class YdbConnectionImpl implements YdbConnection {
     }

     private DataQuery prepareDataQuery(YdbQuery query) throws SQLException {
+        //ensureOpened();
+
         PrepareDataQuerySettings cfg = executor.withTimeouts(new PrepareDataQuerySettings());
         String yql = query.getYqlQuery(null);

-        try (Session session = executor.createSession(ctx)) {
+        try (Session session = getSessionForPrepare()) {
             return executor.call("Preparing Query >>\n" + yql, () -> session.prepareDataQuery(yql, cfg));
         }
     }

+    private Session getSessionForPrepare() throws SQLException {
+        if (state == null) {
+            return executor.createSession(ctx);
+        } else {
+            return state.getSession(ctx, executor);
+        }
+    }
+
     @Override
     public YdbStatement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
         return createStatement(resultSetType, resultSetConcurrency, ResultSet.HOLD_CURSORS_OVER_COMMIT);
```

**Comment by alex268** [comment]
Hello!
There some reasons to use other Session for prepareDataQuery: we are trying not use the session with active transaction for any side work, like prepareDataQuery and explainDataQuery. Additionally we cannot use it with non-transaction methods like scanQuery and schemeQuery. So all these methods always get a new session from the session pool for execution.
This may create additional usage of the session pool, but it doesn't create any deadlocks. The session pool is designed to process the request's count more than the maximum size, but you are right that it may create the performance decreases.
For resolve the performance issues the driver right now uses the pool autoresize option with build-in [thresholding](https://github.com/ydb-platform/ydb-jdbc-driver/blob/e3b19735b095a932c09722305c6af2787ee1c59e/jdbc/src/main/java/tech/ydb/jdbc/context/YdbContext.java#L36). It allows to keep a few extra sessions for side works.
Also we have a plan to implement LRU cache for prepared queries. This cache allows to reduce the usage of prepareDataQuery and the problem will go away

**Comment by alex268** [comment]
This problem was resolved after switching to use QueryService by default in version > 2.3.0. Now query preparing and executing use different kinds of session (TableSession vs QuerySession) so customers never reach maximum limit of session pools
